### ISSUE TITLE
求评测烤串店

### ISSUE THREAD

**Issue by htfy96** [byshen/sdfood#1]
下周打算去吃 [客串烧烤社 Guest Kabob Chinese BBQ](https://goo.gl/maps/eCkyWN2kBV62)，求介绍

**Comment by byshen** [comment]
据说很好啊，我还没去过qwq

**Comment by byplusone** [comment]
focus bbq非常差劲，价格比较高，而且量少
另外就是千万别点所谓的冷面…表示被刷新了难吃的三观
