### ISSUE TITLE
牛排店推荐 Hunters Steakhouse

### ISSUE THREAD

**Issue by MrWhoami** [byshen/sdfood#6]
店名: Hunters Steakhouse
价格: $$$（$25-35 每人，是牛排店里便宜的了，但是按标准就是三个 $）
评分: 3
推荐菜式: prime rib （获奖牛排）
备注: 点 standard 中号就能吃的很饱，还有更大一号的 hunter cut，一般人吃不完，30吃饱，40吃好，好吃不贵，量大价优，环境优雅。另：需要预约。http://www.huntersteakhouse.com/home.html

**Comment by byshen** [comment]
老哥稳
