### ISSUE TITLE
Tasty Noodle House & Tasty Pot

### ISSUE THREAD

**Issue by kqyao** [byshen/sdfood#8]
加入两家自称Tasty的

店名: Tasty Noodle House
价格: $$
评分: 2.5
菜式: 为数不多的上海菜
备注: 去了两次晚餐都要等位15分钟。（评价者是上海人可能有偏见

店名: Tasty Pot
价格: $$
评分: 2
菜式: 台湾式火锅
备注: 每人一个小锅，食量不大的同学点一个锅底就够了。

**Comment by byshen** [comment]
添加了~
